// examples/react-example/src/components/EditorsComponent.tsx
import { Editor } from 'openapi-definition-to-editor';
import * as React from 'react';
import EditorComponent from './EditorComponent';

const EditorsComponent = ({ editors, value }: { value: any; editors: Editor[] }) => {
    const [changes, setChanges] = React.useState({ $set: {}, $unset: {} } as any);
    return (
        <div>
            {(editors || []).map((editor, i) => (
                <EditorComponent key={editor.name + i} editor={editor} value={value} changes={changes} setChanges={setChanges} />
            ))}
        </div>
    );
};

export default EditorsComponent;

// examples/anguler-example/src/app/editors/editors.component.ts
import { Component, OnInit } from '@angular/core';
import { Editor, getEditor, OpenApiDocument } from 'openapi-definition-to-editor';
import openapiSchemaExample from 'openapi-definition-to-editor/src/openapiSchemaExample2.json';

@Component({
    selector: 'app-editors',
    templateUrl: './editors.component.html',
    styleUrls: ['./editors.component.css'],
})
export class EditorsComponent implements OnInit {
    constructor() {}
    editors: Editor[];
    value: any;
    changes: any;
    ngOnInit(): void {
        this.editors = ['DeepMappingSettings'].map(tabName => getEditor((openapiSchemaExample as any) as OpenApiDocument, tabName));
        this.value = {};
        this.changes = { $set: {}, $unset: {} };
        console.log(this.editors);
    }
    setChanges(val: any): void {
        val = val || { $set: {}, $unset: {} };
        this.changes = { ...val };
        console.log(this.changes);
    }
}

<ng-container *ngFor="let editor of editors">
    <app-editor [value]="value" [editor]="editor" [changes]="changes" (setChanges)="setChanges($event)"></app-editor>
</ng-container>
