// examples/react-example/src/components/EditorInputComponent.tsx
import { EditorArrayInput, EditorInput, EditorObjectInput, EditorPrimitiveInput } from 'openapi-definition-to-editor';
import * as React from 'react';
import EditorArrayInputComponent from './EditorArrayInputComponent';
import EditorPrimitiveInputComponent from './EditorPrimitiveInputComponent';
import EditorObjectInputComponent from './EditorObjectInputComponent';
import EditorProps from './EditorProps';

const EditorInputComponent = ({ editorInput, changes, setChanges, value }: EditorProps & { editorInput: EditorInput }) => {
    if (editorInput.editorType === 'EditorPrimitiveInput') {
        return <EditorPrimitiveInputComponent changes={changes} primitiveInput={editorInput as EditorPrimitiveInput} setChanges={setChanges} value={value} />;
    }
    if (editorInput.editorType === 'EditorArrayInput') {
        return <EditorArrayInputComponent changes={changes} arrayInput={editorInput as EditorArrayInput} setChanges={setChanges} value={value} />;
    }
    return <EditorObjectInputComponent changes={changes} objectInput={editorInput as EditorObjectInput} setChanges={setChanges} value={value} />;
};

export default EditorInputComponent;

// examples/anguler-example/src/app/editor-input/editor-input.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { EditorInput } from 'openapi-definition-to-editor';

@Component({
    selector: 'app-editor-input',
    template: `
        <app-editor-primitive-input
            [changes]="changes"
            (setChanges)="setChanges.emit($event)"
            [value]="value"
            *ngIf="editorInput.editorType === 'EditorPrimitiveInput'"
            [primitiveInput]="editorInput"
        ></app-editor-primitive-input>
        <app-editor-array-input
            [changes]="changes"
            (setChanges)="setChanges.emit($event)"
            [value]="value"
            *ngIf="editorInput.editorType === 'EditorArrayInput'"
            [arrayInput]="editorInput"
        ></app-editor-array-input>
        <app-editor-object-input
            [changes]="changes"
            (setChanges)="setChanges.emit($event)"
            [value]="value"
            *ngIf="editorInput.editorType === 'EditorObjectInput'"
            [objectInput]="editorInput"
        ></app-editor-object-input>
    `,
})
export class EditorInputComponent implements OnInit {
    constructor() {}
    @Input() editorInput: EditorInput;
    @Input() changes: any;
    @Output() setChanges = new EventEmitter();
    @Input() value: any;
    ngOnInit(): void {}
}

<app-editor-primitive-input
    [changes]="changes"
    (setChanges)="setChanges.emit($event)"
    [value]="value"
    *ngIf="editorInput.editorType === 'EditorPrimitiveInput'"
    [primitiveInput]="editorInput"
></app-editor-primitive-input>
<app-editor-array-input
    [changes]="changes"
    (setChanges)="setChanges.emit($event)"
    [value]="value"
    *ngIf="editorInput.editorType === 'EditorArrayInput'"
    [arrayInput]="editorInput"
></app-editor-array-input>
<app-editor-object-input
    [changes]="changes"
    (setChanges)="setChanges.emit($event)"
    [value]="value"
    *ngIf="editorInput.editorType === 'EditorObjectInput'"
    [objectInput]="editorInput"
></app-editor-object-input>
