// examples/react-example/src/components/EditorPrimitiveInputComponent.tsx
import { EditorPrimitiveInput, getEditorInputName } from 'openapi-definition-to-editor';
import * as React from 'react';
import EditorProps from './EditorProps';
import * as jp from 'jsonpath';

const EditorPrimitiveInputComponent = ({
    primitiveInput,
    changes,
    setChanges,
    value,
}: EditorProps & {
    primitiveInput: EditorPrimitiveInput;
}) => {
    const onChange = (newVal: any) => setChanges({ $set: { ...changes.$set, [primitiveInput.path]: newVal }, $unset: changes.$unset });
    const pathValue = changes.$set[primitiveInput.path] ?? jp.query(value, '$.' + primitiveInput.path) ?? '';
    const requiredDot = primitiveInput.required ? <span style={{ color: 'red' }}>*</span> : <span />;
    let input = <div />;
    if (primitiveInput.type === 'enum') {
        const options: any[] = primitiveInput.enumNames || primitiveInput.enumValues || [];
        input = (
            <select onChange={e => onChange(e.target.value)} value={pathValue}>
                {options.map(o => (
                    <option key={primitiveInput.path + o}>{o}</option>
                ))}
            </select>
        );
    } else if (primitiveInput.type === 'boolean') {
        input = <input onChange={e => onChange(e.target.checked)} checked={pathValue} type='checkbox' />;
    } else if (primitiveInput.type === 'string') {
        input = <input onChange={e => onChange(e.target.value)} value={pathValue} />;
    } else {
        input = <input onChange={e => onChange(e.target.value)} value={pathValue} type={primitiveInput.type} />;
    }
    return (
        <div>
            <b>{getEditorInputName(primitiveInput)}:</b> {requiredDot} {input}
        </div>
    );
};
export default EditorPrimitiveInputComponent;

// examples/anguler-example/src/app/editor-primitive-input/editor-primitive-input.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { EditorPrimitiveInput, getEditorInputName } from 'openapi-definition-to-editor';
import * as jp from 'jsonpath';

@Component({
    selector: 'app-editor-primitive-input',
    templateUrl: './editor-primitive-input.component.html',
    styleUrls: ['./editor-primitive-input.component.css'],
})
export class EditorPrimitiveInputComponent implements OnInit {
    constructor() {}
    @Input() changes: any;
    @Output() setChanges = new EventEmitter();
    @Input() value: any;
    @Input() primitiveInput: EditorPrimitiveInput;
    pathValue: any;
    enumOptions: any[];
    ngOnInit(): void {
        this.value = this.value || {};
        this.pathValue = this.changes.$set[this.primitiveInput.path] ?? jp.query(this.value, '$.' + this.primitiveInput.path) ?? '';
        this.enumOptions = this.primitiveInput.enumNames || this.primitiveInput.enumValues || [];
    }
    setValue(newVal) {
        this.setChanges.emit({ $set: { ...this.changes.$set, [this.primitiveInput.path]: newVal }, $unset: this.changes.$unset });
    }
    getName() {
        return getEditorInputName(this.primitiveInput);
    }
}

<div>
    <b>{{ getName() }}:</b> <span style="color: 'red'">*</span>
    <select [value]="pathValue" *ngIf="primitiveInput.type === 'enum'" (change)="setValue($event.target.value)">
        <option *ngFor="let option of enumOptions">{{ option }}</option>
    </select>
    <input [value]="pathValue" type="checkbox" *ngIf="primitiveInput.type === 'boolean'" (change)="setValue($event.target.checked)" />
    <input [value]="pathValue" type="text" *ngIf="primitiveInput.type === 'string'" (change)="setValue($event.target.value)" />
    <input [value]="pathValue" type="number" *ngIf="primitiveInput.type === 'number'" (change)="setValue($event.target.value)" />
    <input [value]="pathValue" type="date" *ngIf="primitiveInput.type === 'date'" (change)="setValue($event.target.value)" />
</div>
