// examples/anguler-example/src/app/editor/editor.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Editor } from 'openapi-definition-to-editor';

@Component({
    selector: 'app-editor',
    templateUrl: './editor.component.html',
    styleUrls: ['./editor.component.css'],
})
export class EditorComponent implements OnInit {
    constructor() {}
    @Input() editor: Editor;
    changes: any;
    getChanges;
    ngOnInit(): void {
        this.changes = {};
    }
    setChanges(val: any): void {
        val = val || {};
        this.changes = { ...this.changes, ...val };
        console.log(this.changes);
    }
}

<div>
    <h1>{{ editor.name }}</h1>
    <div style="padding-left: '20px'">
        <app-editor-input
            *ngFor="let input of editor.inputs"
            [value]="{}"
            [changes]="changes"
            [setChanges]="setChanges"
            [editorInput]="input"
        ></app-editor-input>
    </div>
</div>

// examples/react-example/src/components/EditorComponent.tsx
import { Editor } from 'openapi-definition-to-editor';
import * as React from 'react';
import EditorInputComponent from './EditorInputComponent';

const EditorComponent = ({ editor, value }: { value: any; editor: Editor }) => {
    const inputs = editor.inputs || [];
    const [changes, setChanges] = React.useState({} as any);
    console.log(changes);
    return (
        <div>
            <h1>{editor.name}</h1>
            <div style={{ paddingLeft: '20px' }}>
                {inputs.map((editorInput, i) => (
                    <EditorInputComponent key={editorInput.path + i} value={value} changes={changes} setChanges={setChanges} editorInput={editorInput} />
                ))}
            </div>
        </div>
    );
};

export default EditorComponent;
