// examples/anguler-example/src/app/editor-object-input/editor-object-input.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { EditorInput, EditorObjectInput, getEditorInputName } from 'openapi-definition-to-editor';

@Component({
    selector: 'app-editor-object-input',
    templateUrl: './editor-object-input.component.html',
    styleUrls: ['./editor-object-input.component.css'],
})
export class EditorObjectInputComponent implements OnInit {
    constructor() {}
    @Input() changes: any;
    @Output() setChanges = new EventEmitter();
    @Input() value: any;
    @Input() objectInput: EditorObjectInput;
    switchableSelected: string;
    ngOnInit(): void {
        this.objectInput.properties = this.objectInput.properties || [];
        this.objectInput.switchableOptions = this.objectInput.switchableOptions || [];
        this.objectInput.switchableObjects = this.objectInput.switchableObjects || [];
    }
    fixIndexPath(x: EditorInput) {
        x.path = `${this.objectInput.path}.${getEditorInputName(x)}`;
        return x;
    }
    setSwitchableSelected(val: string) {
        this.switchableSelected = val;
    }
    getName() {
        return getEditorInputName(this.objectInput);
    }
}

<div style="padding-left: '20px'">
    <b>{{ getName() }}</b> :
    <span *ngIf="objectInput.switchable">
        <b *ngIf="objectInput.switchable"><u>switchable:</u> </b>
        <button (click)="setSwitchableSelected('common')">common</button>
        <button (click)="setSwitchableSelected(switchableName)" *ngFor="let switchableName of objectInput.switchableOptions">{{ switchableName }}</button>
    </span>
    <div style="padding-left: '20px'">
        <b *ngIf="objectInput.switchable">
            <u>common:</u>
        </b>
        <app-editor-input
            [changes]="changes"
            [editorInput]="fixIndexPath(x)"
            (setChanges)="setChanges.emit($event)"
            [value]="value"
            *ngFor="let x of objectInput.properties"
        ></app-editor-input>

        <div *ngFor="let switchableObject of objectInput.switchableObjects; let i = index">
            <div *ngIf="switchableSelected == objectInput.switchableOptions![i]">
                <b>
                    <u>{{ objectInput.switchableOptions![i] }}</u>
                </b>
                <app-editor-input
                    [changes]="changes"
                    [editorInput]="fixIndexPath(switchableObject)"
                    (setChanges)="setChanges.emit($event)"
                    [value]="value"
                ></app-editor-input>
            </div>
        </div>
    </div>
</div>

// examples/react-example/src/components/EditorObjectInputComponent.tsx
import { EditorInput, EditorObjectInput, getEditorInputName } from 'openapi-definition-to-editor';
import * as React from 'react';
import { useState } from 'react';
import EditorInputComponent from './EditorInputComponent';
import EditorProps from './EditorProps';

const EditorObjectInputComponent = ({ objectInput, changes, setChanges, value }: EditorProps & { objectInput: EditorObjectInput }) => {
    const [switchableSelected, setSwitchableSelected] = useState('' as string);
    const fixIndexPath = (x: EditorInput) => {
        x.path = `${objectInput.path}.${getEditorInputName(x)}`;
        return x;
    };
    objectInput.properties = objectInput.properties || [];
    const propsComponents = objectInput.properties.map((x, i) => (
        <EditorInputComponent key={x.path + i} changes={changes} editorInput={fixIndexPath(x)} setChanges={setChanges} value={value} />
    ));
    if (objectInput.switchable) {
        const commonProps = (
            <div style={{ paddingLeft: '20px' }}>
                <b>
                    <u>common:</u>
                </b>
                {propsComponents}
            </div>
        );
        objectInput.switchableOptions = objectInput.switchableOptions || [];
        objectInput.switchableObjects = objectInput.switchableObjects || [];
        return (
            <div>
                <b>{getEditorInputName(objectInput)}</b>:
                <b>
                    <u>switchable:</u>
                </b>
                {['common', ...objectInput.switchableOptions].map(s => (
                    <button key={s} onClick={() => setSwitchableSelected(s)}>
                        {s}
                    </button>
                ))}
                {commonProps}
                {objectInput.switchableObjects.map((x, i) => (
                    <div key={x.path + i} style={{ paddingLeft: '20px' }}>
                        {switchableSelected === objectInput.switchableOptions![i] && (
                            <>
                                <b>
                                    <u>{objectInput.switchableOptions![i]}</u>
                                </b>
                                {<EditorInputComponent changes={changes} editorInput={fixIndexPath(x)} setChanges={setChanges} value={value} />}
                            </>
                        )}
                    </div>
                ))}
            </div>
        );
    }
    return (
        <div style={{ paddingLeft: '20px' }}>
            <b>{getEditorInputName(objectInput)}</b>: <div style={{ paddingLeft: '20px' }}>{propsComponents}</div>
        </div>
    );
};

export default EditorObjectInputComponent;
