// examples/anguler-example/src/app/editor-array-input/editor-array-input.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { EditorArrayInput, getEditorInputName } from 'openapi-definition-to-editor';

@Component({
    selector: 'app-editor-array-input',
    templateUrl: './editor-array-input.component.html',
    styleUrls: ['./editor-array-input.component.css'],
})
export class EditorArrayInputComponent implements OnInit {
    constructor() {}
    @Input() changes: any;
    @Input() setChanges: (val: any) => void;
    @Input() value: any;
    @Input() arrayInput: EditorArrayInput;
    items: any[] = [];
    name: string;
    arrayPath: string;
    ngOnInit(): void {
        this.arrayPath = this.arrayInput.path.replace('[i]', ``);
        this.items = this.value[this.arrayPath] || [];
        this.name = getEditorInputName(this.arrayInput).replace('[i]', ``);
    }
    deleteItem(index: number) {
        this.changes = this.changes || {};
        this.items[index] = this.items[index] || {};
        this.items[index]['x-editorDeleted'] = true;
        const prefixKey = this.arrayInput.itemInput.path.replace('[i]', `[${index}]`);
        Object.keys(this.changes)
            .filter(key => key.includes(prefixKey))
            .forEach(key => delete this.changes[key]);
        this.setChanges({ ...this.changes });
    }
    addItem() {
        this.items.push({ 'x-editorDeleted': false });
    }
    modifyIndex(i: number) {
        const itemInput = Object.assign({}, this.arrayInput.itemInput);
        itemInput.path = itemInput.path.replace('[i]', `[${i}]`);
        return itemInput;
    }
}

<div>
    <b>{{ name }}:</b><button (click)="addItem()">Add</button>
    <div *ngFor="let item of items; let i = index">
        <div *ngIf="!item['x-editorDeleted']">
            <app-editor-input [editorInput]="modifyIndex(i)" [changes]="changes" [setChanges]="setChanges" [value]="value"></app-editor-input>
            <button (click)="deleteItem(i)">Delete</button>
        </div>
    </div>
</div>

// examples/react-example/src/components/EditorArrayInputComponent.tsx
import { EditorArrayInput, getEditorInputName } from 'openapi-definition-to-editor';
import * as React from 'react';
import EditorInputComponent from './EditorInputComponent';
import EditorProps from './EditorProps';

const EditorArrayInputComponent = ({
    arrayInput,
    changes,
    setChanges,
    value,
}: EditorProps & {
    arrayInput: EditorArrayInput;
}) => {
    const arrayPath = arrayInput.path.replace('[i]', ``);
    const [items, setItems] = React.useState((value[arrayPath] as any[]) || ([] as any[]));
    const modifyIndex = (i: number) => {
        const itemInput = Object.assign({}, arrayInput.itemInput);
        itemInput.path = itemInput.path.replace('[i]', `[${i}]`);
        return itemInput;
    };
    const deleteItem = (index: number) => {
        items[index]['x-editorDeleted'] = true;
        const prefixKey = arrayInput.itemInput.path.replace('[i]', `[${index}]`);
        Object.keys(changes)
            .filter(key => key.includes(prefixKey))
            .forEach(key => delete changes[key]);
        setChanges({ ...changes });
        setItems([...items]);
    };
    return (
        <div>
            {<b>{getEditorInputName(arrayInput).replace('[i]', ``)}:</b>} <button onClick={() => setItems([...items, {}])}>Add</button>
            {items.map((listItem, index) => (
                <div key={arrayInput.path + index}>
                    {!listItem['x-editorDeleted'] && (
                        <>
                            <EditorInputComponent editorInput={modifyIndex(index)} changes={changes} setChanges={setChanges} value={value} />
                            <button onClick={() => deleteItem(index)}>Delete</button>
                        </>
                    )}
                </div>
            ))}
        </div>
    );
};
export default EditorArrayInputComponent;
